-- ============================================================
-- schema.sql — Database Schema for OTC Derivatives Simulation
-- ============================================================
-- This file defines all the tables we use to store trade data.
-- SQLite is used — it's a lightweight database stored in a single file.
--
-- TABLES:
--   1. trades            — All OTC trade records
--   2. mtm_valuations    — Daily mark-to-market values
--   3. margin_calls      — Margin calls generated
--   4. collateral        — Collateral posted/received
--   5. lifecycle_events  — Trade state changes
--   6. settlements       — Final cash settlements
--   7. reconciliation    — Position matching results
-- ============================================================


-- ── TABLE 1: trades ──────────────────────────────────────────
-- Stores the core details of each OTC trade when it is booked.
-- Think of this as the "trade ticket" — the master record.

CREATE TABLE IF NOT EXISTS trades (
    trade_id            TEXT PRIMARY KEY,       -- Unique ID e.g. TRD-00001
    instrument_type     TEXT NOT NULL,          -- IRS, FX_FWD, CDS, XCCY
    instrument_name     TEXT,                   -- Full name of instrument
    trade_date          TEXT NOT NULL,          -- Date the trade was booked
    start_date          TEXT NOT NULL,          -- Date the trade becomes effective
    maturity_date       TEXT NOT NULL,          -- Date the trade expires
    notional            REAL NOT NULL,          -- Face value of the trade
    currency            TEXT NOT NULL,          -- Currency (INR, USD, EUR, GBP)
    notional_inr        REAL,                   -- Notional converted to INR
    fixed_rate          REAL,                   -- Fixed interest rate (for IRS)
    floating_rate       REAL,                   -- Current floating rate
    fx_rate             REAL,                   -- FX rate at trade inception
    direction           TEXT,                   -- "PAY_FIXED" or "RECEIVE_FIXED"
    counterparty_id     TEXT NOT NULL,          -- Who is on the other side
    counterparty_name   TEXT,                   -- Readable name
    counterparty_country TEXT,                  -- Country code (IN, US, GB etc)
    jurisdiction        TEXT,                   -- "INDIA" or "INTERNATIONAL"
    clearing_venue      TEXT,                   -- CCIL / LCH / Bilateral
    status              TEXT DEFAULT 'ACTIVE',  -- Current lifecycle state
    regulatory_regime   TEXT,                   -- RBI/SEBI or ISDA/Dodd-Frank
    created_at          TEXT DEFAULT CURRENT_TIMESTAMP
);


-- ── TABLE 2: mtm_valuations ──────────────────────────────────
-- Stores the daily mark-to-market (MTM) value of every trade.
-- MTM = current market value of the trade.
-- If positive → counterparty owes us money.
-- If negative → we owe counterparty money.

CREATE TABLE IF NOT EXISTS mtm_valuations (
    id                  INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id            TEXT NOT NULL,          -- Which trade
    valuation_date      TEXT NOT NULL,          -- Which day
    mtm_value           REAL NOT NULL,          -- MTM in trade currency
    mtm_value_inr       REAL NOT NULL,          -- MTM converted to INR
    delta               REAL,                   -- Change in MTM from previous day
    pnl_daily           REAL,                   -- Daily profit or loss
    fx_rate_today       REAL,                   -- FX rate used today
    discount_factor     REAL,                   -- Time value of money factor
    valuation_method    TEXT,                   -- "MARK_TO_MARKET" or "MARK_TO_MODEL"
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
);


-- ── TABLE 3: margin_calls ────────────────────────────────────
-- Stores margin calls generated by the margin engine.
-- A margin call is a demand for more collateral when MTM moves against you.

CREATE TABLE IF NOT EXISTS margin_calls (
    call_id             TEXT PRIMARY KEY,       -- Unique margin call ID
    trade_id            TEXT,                   -- Related trade (or NULL for portfolio-level)
    counterparty_id     TEXT NOT NULL,          -- Who the call is to/from
    call_date           TEXT NOT NULL,          -- Date call was issued
    margin_type         TEXT NOT NULL,          -- "INITIAL_MARGIN" or "VARIATION_MARGIN"
    call_amount         REAL NOT NULL,          -- Amount demanded (in call currency)
    call_currency       TEXT,                   -- Currency of the call
    call_amount_inr     REAL,                   -- Amount in INR equivalent
    direction           TEXT,                   -- "CALL" (we demand) or "RETURN" (we give back)
    status              TEXT DEFAULT 'PENDING', -- PENDING / MET / DISPUTED / FAILED
    due_date            TEXT,                   -- Deadline to meet the call
    settled_date        TEXT,                   -- When it was actually met
    settled_amount      REAL,                   -- Amount actually received
    regulatory_basis    TEXT,                   -- RBI or ISDA basis for the call
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
);


-- ── TABLE 4: collateral ──────────────────────────────────────
-- Tracks all collateral posted and received.
-- Collateral = assets pledged as security for the trade.

CREATE TABLE IF NOT EXISTS collateral (
    collateral_id       TEXT PRIMARY KEY,       -- Unique collateral record ID
    trade_id            TEXT,                   -- Which trade it covers
    counterparty_id     TEXT,                   -- Counterparty involved
    posting_date        TEXT NOT NULL,          -- When collateral was posted
    collateral_type     TEXT NOT NULL,          -- E.g. "GOI_BONDS", "USD_CASH"
    collateral_desc     TEXT,                   -- Description
    gross_value         REAL NOT NULL,          -- Market value before haircut
    haircut_pct         REAL NOT NULL,          -- Haircut percentage applied
    net_value           REAL NOT NULL,          -- Value after haircut (what counts)
    currency            TEXT,                   -- Currency
    net_value_inr       REAL,                   -- Net value in INR
    direction           TEXT,                   -- "POSTED" (we gave) or "RECEIVED" (we got)
    status              TEXT DEFAULT 'ACTIVE',  -- ACTIVE / RETURNED / SUBSTITUTED
    return_date         TEXT,                   -- When returned (if applicable)
    eligible_under      TEXT,                   -- "RBI" or "ISDA" eligible
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
);


-- ── TABLE 5: lifecycle_events ────────────────────────────────
-- An audit log of every state change in a trade's life.
-- This is important for compliance — regulators want to see history.

CREATE TABLE IF NOT EXISTS lifecycle_events (
    event_id            INTEGER PRIMARY KEY AUTOINCREMENT,
    trade_id            TEXT NOT NULL,          -- Which trade
    event_date          TEXT NOT NULL,          -- When it happened
    event_type          TEXT NOT NULL,          -- BOOKED, CONFIRMED, MATURED, SETTLED...
    from_status         TEXT,                   -- Previous status
    to_status           TEXT,                   -- New status
    event_description   TEXT,                   -- Human-readable description
    triggered_by        TEXT,                   -- "SYSTEM" or "MANUAL"
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
);


-- ── TABLE 6: settlements ─────────────────────────────────────
-- Records the final cash settlement when a trade ends.
-- On expiry, one party pays the other based on the final MTM.

CREATE TABLE IF NOT EXISTS settlements (
    settlement_id       TEXT PRIMARY KEY,
    trade_id            TEXT NOT NULL,
    settlement_date     TEXT NOT NULL,
    settlement_type     TEXT,                   -- "CASH" or "PHYSICAL"
    final_mtm           REAL,                   -- Final mark-to-market at maturity
    settlement_amount   REAL NOT NULL,          -- How much was paid
    settlement_currency TEXT,
    settlement_amount_inr REAL,
    payer               TEXT,                   -- Who paid
    receiver            TEXT,                   -- Who received
    payment_status      TEXT DEFAULT 'PENDING', -- PENDING / COMPLETED / FAILED
    netting_applied     INTEGER DEFAULT 0,      -- 1 if close-out netting was applied
    legal_basis         TEXT,                   -- "ISDA_MA" or "RBI_GUIDELINES"
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
);


-- ── TABLE 7: reconciliation ──────────────────────────────────
-- Results of the daily reconciliation run.
-- We compare our records with the counterparty's records.

CREATE TABLE IF NOT EXISTS reconciliation (
    recon_id            INTEGER PRIMARY KEY AUTOINCREMENT,
    recon_date          TEXT NOT NULL,          -- When reconciliation ran
    trade_id            TEXT,
    counterparty_id     TEXT,
    our_mtm             REAL,                   -- MTM as per our books
    counterparty_mtm    REAL,                   -- MTM as per their books
    difference          REAL,                   -- Gap between the two
    difference_pct      REAL,                   -- Gap as a percentage
    status              TEXT,                   -- MATCHED / BREAK / AUTO_RESOLVED
    break_category      TEXT,                   -- Type of break (if any)
    break_description   TEXT,                   -- Details of what doesn't match
    resolved            INTEGER DEFAULT 0,      -- 1 = resolved, 0 = pending
    resolution_notes    TEXT,                   -- How it was resolved
    FOREIGN KEY (trade_id) REFERENCES trades(trade_id)
);


-- ── INDEXES for faster queries ───────────────────────────────
CREATE INDEX IF NOT EXISTS idx_mtm_trade_date     ON mtm_valuations(trade_id, valuation_date);
CREATE INDEX IF NOT EXISTS idx_margin_cp_date     ON margin_calls(counterparty_id, call_date);
CREATE INDEX IF NOT EXISTS idx_collateral_trade   ON collateral(trade_id);
CREATE INDEX IF NOT EXISTS idx_lifecycle_trade    ON lifecycle_events(trade_id);
CREATE INDEX IF NOT EXISTS idx_recon_date         ON reconciliation(recon_date);
CREATE INDEX IF NOT EXISTS idx_trades_status      ON trades(status);
CREATE INDEX IF NOT EXISTS idx_trades_cp          ON trades(counterparty_id);
